version: "3"

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env-postgres
    ports:
      - 5432:5432
